django/mysite/data_tower/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views


app_name = "data_tower"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^artilce/column/$', views.articleColumns, name = "articleColumns"),
    url(r'^artilce/column/add/$', views.addArticleColumn, name = "addArticleColumn"),
    url(r'^artilce/stat/$', views.articleStat, name = "articleStat"),
]

django/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^data_tower/', include('data_tower.urls')),
    url(r'^admin/', admin.site.urls),
]

django/mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
	#ex :/polls/
    # url(r'^$', views.index, name='index'),
    # #ex :/polls/5/
    # # url(r'^specifics/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # #ex : /polls/5/result/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultView.as_view(), name='results'),
    # #ex : /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django/mysite/data_tower/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

# from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
# Create your models here.

@python_2_unicode_compatible
class ArticleColumn(models.Model):
	column_id = models.IntegerField(default=0)
	column_text = models.CharField(max_length = 100, default="未知分类")

	# def __init__(self):
	# 	self.column_id = 0

	# def __init__(self, column_id, column_text):
	# 	self.column_id = column_id
	# 	self.column_text = column_text

	def __str__(self):
		return self.column_text

@python_2_unicode_compatible
class Article(models.Model):
	articleColumn = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, null = True, name="article_column")
	article_title = models.CharField(max_length=500)
	article_url = models.CharField(max_length = 1000)

	def __str__(self):
		return self.article_title


@python_2_unicode_compatible
class ArticleStat(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	views = models.IntegerField(default = 0)

	def __str__(self):
		toString = "Articel: %s, Views: %d" % (self.column_text, self.views)
		return toString

@python_2_unicode_compatible
class ArticleStatDetail(models.Model):
	article_id = models.IntegerField(default = 0)
	stat_data = models.DateTimeField('stat collect')
	views = models.IntegerField(default = 0)

	def __str__(self):
		toString = "Articel: %s, Current Views: %d" % (self.column_text, self.views)
		return toString

django/mysite/polls/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.
@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django/mysite/data_tower/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.template import loader
from django.urls import reverse

from .models import Article
from .models import ArticleColumn
from .models import ArticleStat
from .models import ArticleStatDetail


# Create your views here.

def index(request):
	return render(request, 'data_tower/index.html', {})

# class IndexView(ListView):

def addArticleColumn(request):
	articleColumnId = request.POST['articleColumnId']
	articleColumnText = request.POST['articleColumnText']
	articleColumn = ArticleColumn()
	articleColumn.column_id = articleColumnId
	articleColumn.column_text = articleColumnText
	articleColumn.save()
	return HttpResponseRedirect(reverse('data_tower:articleColumns'))

def articleColumns(request):
	articleColumns = ArticleColumn.objects.all()
	return render(request, "data_tower/article_columns.html", {'articleColumns': articleColumns})

def articleStat(request, articeId):
	if articeId:
		articleStats = ArticleStat.objects.filter(article_id = articeId)
	else:
		articleStats = ArticleStat.objects.order_by("-views")[:10]
	return render(request, "data_tower/article_stat.html", {'articleStats': articleStats})

django/mysite/polls/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question
from .models import Choice

from django.template import loader

# from django.shortcuts



# Create your views here.

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""Return the last five published questions"""
		return Question.objects.order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = "polls/detail.html"	

class ResultView(generic.DetailView):
	model = Question
	template_name = "polls/results.html"

# def index(request):
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]	
# 	context = {
# 		'latest_question_list': latest_question_list,
# 	}
# 	return render(request, 'polls/index.html', context)
	# template = loader.get_template('polls/index.html')
	# return HttpResponse(template.render(context, request))
	# output = ", ".join([q.question_text for q in latest_question_list])
	# return HttpResponse(output)	
    # return HttpResponse("Hello, world. You're at the polls index.")

#...
# def detail(request, question_id):
	# try:
	# 	question = Question.objects.get(pk = question_id)
	# except Question.DoesNotExist:
	# 	raise Http404("Question dose not exists")

	# question = get_object_or_404(Question, pk=question_id)

	# return render(request, 'polls/detail.html', {'question': question})


    # return HttpResponse("You are looking at question %s." % question_id)

# def results(request, question_id):
    # response = "You are looking at results of question %s."
    # return HttpResponse(response % question_id)
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)

	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
				'question': question,
				'error_message': "You didn't select a choice.",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()

		return HttpResponseRedirect(reverse('polls:results', args=(question_id, )))

    # return HttpResponse("You are voting on question %s." % question_id)

django/mysite/data_tower/templates/data_tower/article_columns.html
<form action="{% url 'data_tower:addArticleColumn' %}" method="post">
	{% csrf_token %}
	<label for="c-text">百度百家号分类Id:</label>
	<input id="c-text" type="input" name="articleColumnId" value=""/>
	<br/>
	<label for="c-text">百度百家号分类描述:</label>
	<input id="c-id" type="input" name="articleColumnText" value=""/>
	<br/>
	<input type="submit" value="Add"/>
</form>
{% if articleColumns %}
	<table>
		<tr>
			<th>Id</th>
			<th>原始Id</th>
			<th>名称</th>
		</tr>
	{% for column in articleColumns %}
		<tr>
			<td>{{ column.id }}</td>
			<td>{{ column.column_id }}</td>
			<td>{{ column.column_text }}</td>
		</tr>
	{% endfor %}
	</table>
{% endif %}

django/mysite/data_tower/templates/data_tower/index.html
<a href="{% url 'data_tower:articleStat' %}">Stat</a>
<br/>
<a href="{% url 'data_tower:articleColumns' %}">Article column</a>

django/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

<!-- <ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text }}</li>
	{% endfor %}
</ul>

 -->
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice_{{forloop.counter}}" value="{{ choice.id }}"/>
	<label for="choice_{{forloop.counter}}">{{ choice.choice_text }}</label><br/>
	{% endfor %}
	<input type="submit" value="Vote"/>
</form>

django/mysite/polls/templates/polls/index.html
{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
		<!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
		<li><a href='{% url 'polls:detail' question.id %}'>{{ question.question_text }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No polls are avaiable.</p>
{% endif %}

django/mysite/polls/templates/polls/results.html
<h1>
	{{ question.question_text }}
</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize  }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id%}">Vote again?</a>